[package]
name = "steve-challenge-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
discord = { git = "https://github.com/SpaceManiac/discord-rs" }
dotenv = "0.15.0"
reqwest = { version = "0.11.18", features = ["blocking"] }
